version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  opencart:
    image: 'docker.io/bitnami/opencart:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './admin/controller/extension/payment:/opt/bitnami/opencart/admin/controller/extension/payment'
      - './admin/language/en-gb/extension/payment:/opt/bitnami/opencart/admin/language/en-gb/extension/payment'
      - './admin/view/image/payment:/opt/bitnami/opencart/admin/view/image/payment'
      - './admin/view/template/extension/payment:/opt/bitnami/opencart/admin/view/template/extension/payment'
      - './catalog/controller/extension/payment:/opt/bitnami/opencart/catalog/controller/extension/payment'
      - './catalog/language/en-gb/extension/payment:/opt/bitnami/opencart/catalog/language/en-gb/extension/payment'
      - './catalog/model/extension/payment:/opt/bitnami/opencart/catalog/model/extension/payment'
      - './catalog/view/theme/default/template/extension/payment:/opt/bitnami/opencart/catalog/view/theme/default/template/extension/payment'
      # - './opencart_data:/bitnami/opencart'
      # - './opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
